apiVersion: v1
kind: Pod
metadata:
  name: demoapp
  labels:
    name: myappnginx
spec:
  containers:
  - name: myapp_nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
