apiVersion: v1
kind: Pod
metadata:
  name: demoapp
  labels:
    name: myappnginx
spec:
  containers:
  - name: myapp-nginx
    image: nginx:latest
    resources:
      limits:
        memory: "120Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
